wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1713200570.864549
    t:
      1:
      - 1
      - 11
      - 12
      - 41
      - 45
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 12
      - 41
      - 45
      - 49
      - 51
      - 55
      - 71
      3:
      - 13
      - 15
      - 23
      4: 3.10.6
      5: 0.14.0
      6: 4.37.2
      8:
      - 3
      - 5
