wandb:
  key_wandb: ac12c873f730f05f115d320f73a1a908c5db8470
  project: "Text-to-image"
  tags: "LDM"
  name: "LDM-BASE"
input_perturbation : 0
pretrained_model_name_or_path : "OFA-Sys/small-stable-diffusion-v0"
revision : None
variant : None
dataset_name : None
dataset_config_name : None
train_data_dir : None
image_column : "image"
caption_column : "text"
max_train_samples : None
validation_prompts : None
output_dir : "sd-model-finetuned"
cache_dir : None
seed : 32
resolution : 224
center_crop : False
random_flip : False
train_batch_size : 8
num_train_epochs : 100
max_train_steps : None
gradient_accumulation_steps : 1
gradient_checkpointing : False
learning_rate : 1e-4
scale_lr : False
lr_scheduler : "constant"
lr_warmup_steps : 500
snr_gamma : None
use_8bit_adam : True
allow_tf32 : False
use_ema : False
non_ema_revision : None
dataloader_num_workers : 0
adam_beta1 : 0.9
adam_beta2 : 0.999
adam_weight_decay : 1e-2
adam_epsilon : 1e-08
max_grad_norm : 1.0
push_to_hub : False
hub_token : None
prediction_type : None
hub_model_id : None
logging_dir : "logs"
mixed_precision : 'no'
report_to : "wandb"
local_rank : -1
checkpointing_steps : 500
checkpoints_total_limit : 2
resume_from_checkpoint : None
enable_xformers_memory_efficient_attention : False
noise_offset : 0
validation_epochs : 2
tracker_project_name : "text2image-fine-tune"
data:
  train: /kaggle/input/data-train/data_train.json
  eval: /kaggle/input/data-train/data_test.json
  size: 224

